name: Co-Authored-By Linter
description: Check Git commit messages for invalid "Co-authored-by:" lines
author: Gin
branding:
  icon: "check"
  color: "white"
inputs:
  STRICT_MODE:
    description: 'Enable strict mode for fail-on-warning behavior'
    required: false
    default: 'false'
  BASE_REF:
    description: 'Git branch to check against'
    required: false
    default: 'main'
runs:
  using: "docker"
  image: "Dockerfile"
